- id: shfmt
  name: shfmt
  description: Shell source code formatter (native install)
  language: golang
  additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.5.1]
  entry: shfmt
  args: [-w, -s]
  types: [shell]
  stages: [commit, merge-commit, push, manual]

- id: shfmt-docker
  name: shfmt
  description: Shell source code formatter (Docker image)
  language: docker_image
  entry: --net none mvdan/shfmt:v3.5.1
  args: [-w, -s]
  types: [shell]
  stages: [commit, merge-commit, push, manual]
